export interface User {
  id?: string; // Optional for new users, generated by json-server
  firstName: string;
  lastName: string;
  email: string;
  password?: string; // Will be plain text for json-server demo
  phone?: string;
  role: 'USER' | 'ADMIN' | 'TEAMLEADER';
}
